package com.quantstation.strategy.signals;

import com.quantstation.domain.Order;

import java.time.Instant;
import java.util.UUID;

/**
 * Trading signal generated by a Strategy.
 *
 * <p>Signals carry the trading decision from the Strategy engine to the OMS.
 * They include metadata about why the signal was generated for audit purposes.
 *
 * @param signalId      Unique signal identifier
 * @param strategyName  Name of the strategy that generated this signal
 * @param symbol        Target symbol
 * @param side          BUY or SELL
 * @param orderType     MARKET, LIMIT, etc.
 * @param quantity      Desired quantity
 * @param limitPrice    Limit price (0 for market orders)
 * @param stopPrice     Stop price (0 if not applicable)
 * @param confidence    Strategy confidence score (0.0 to 1.0)
 * @param reason        Human-readable reason for the signal
 * @param timestamp     When the signal was generated
 */
public record Signal(
        String signalId,
        String strategyName,
        String symbol,
        Order.Side side,
        Order.OrderType orderType,
        double quantity,
        double limitPrice,
        double stopPrice,
        double confidence,
        String reason,
        Instant timestamp
) {
    /**
     * Create a simple market buy signal.
     */
    public static Signal marketBuy(String strategy, String symbol,
                                    double qty, String reason) {
        return new Signal(UUID.randomUUID().toString(), strategy, symbol,
                Order.Side.BUY, Order.OrderType.MARKET, qty,
                0.0, 0.0, 1.0, reason, Instant.now());
    }

    /**
     * Create a simple market sell signal.
     */
    public static Signal marketSell(String strategy, String symbol,
                                     double qty, String reason) {
        return new Signal(UUID.randomUUID().toString(), strategy, symbol,
                Order.Side.SELL, Order.OrderType.MARKET, qty,
                0.0, 0.0, 1.0, reason, Instant.now());
    }

    /**
     * Create a limit buy signal.
     */
    public static Signal limitBuy(String strategy, String symbol,
                                   double qty, double price, String reason) {
        return new Signal(UUID.randomUUID().toString(), strategy, symbol,
                Order.Side.BUY, Order.OrderType.LIMIT, qty,
                price, 0.0, 1.0, reason, Instant.now());
    }

    /**
     * Convert this signal to an Order for submission to the OMS.
     */
    public Order toOrder() {
        return new Order(symbol, side, orderType, quantity, limitPrice, stopPrice);
    }
}
