// ═══════════════════════════════════════════════════════
// QuantStation — Portfolio Mock Data (SPEC-007)
// ═══════════════════════════════════════════════════════
// Realistic mock data matching production data shapes.
// Swap to live WebSocket/REST endpoints via usePortfolioData hook.

import type {
  PortfolioData,
  AccountSummaryData,
  PortfolioPosition,
  RiskMetrics,
  SectorExposureItem,
  StrategyAllocationItem,
  MarketExposureData,
  PositionRisk,
  AIHealthItem,
  PerformanceAttributionData,
  PortfolioOrder,
  PortfolioAlert,
  AIRecommendation,
  TimelineEvent,
} from './types'

// ── Account Summary ────────────────────────────────────

const mockAccount: AccountSummaryData = {
  netLiquidation: 2_435_782,
  cash: 412_350,
  buyingPower: 1_824_600,
  marginRemaining: 985_400,
  portfolioValue: 2_023_432,
  todayReturn: 1.77,
  ytdReturn: 24.3,
  realizedPnl: 18_720,
  unrealizedPnl: 23_630,
  totalPnl: 42_350,
  commissions: 287.40,
  borrowFees: 42.10,
  interest: 156.80,
  grossExposure: 2_400_000,
  netExposure: 1_200_000,
}

// ── Positions ──────────────────────────────────────────

const mockPositions: PortfolioPosition[] = [
  {
    symbol: 'PLTR',
    companyName: 'Palantir Technologies',
    sector: 'Technology',
    quantity: 1000,
    avgCost: 120.30,
    lastPrice: 126.70,
    marketValue: 126_700,
    todayPnl: 6_400,
    unrealizedPnl: 6_400,
    realizedPnl: 2_100,
    riskPercent: 1.8,
    allocationPercent: 5.2,
    stopPrice: 117.50,
    targetPrice: 135.00,
    rMultiple: 2.3,
    holdingDays: 12,
    strategy: 'Momentum',
    aiScore: 94,
    confidence: 87,
    hmmRegime: 'Bull',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'NVDA',
    companyName: 'NVIDIA Corporation',
    sector: 'Technology',
    quantity: 200,
    avgCost: 175.80,
    lastPrice: 182.40,
    marketValue: 36_480,
    todayPnl: 1_320,
    unrealizedPnl: 1_320,
    realizedPnl: 4_800,
    riskPercent: 2.1,
    allocationPercent: 1.5,
    stopPrice: 170.00,
    targetPrice: 195.00,
    rMultiple: 1.1,
    holdingDays: 8,
    strategy: 'Swing',
    aiScore: 92,
    confidence: 84,
    hmmRegime: 'Bull',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'AMD',
    companyName: 'Advanced Micro Devices',
    sector: 'Technology',
    quantity: 500,
    avgCost: 148.60,
    lastPrice: 146.30,
    marketValue: 73_150,
    todayPnl: -1_150,
    unrealizedPnl: -1_150,
    realizedPnl: 320,
    riskPercent: 0.9,
    allocationPercent: 3.0,
    stopPrice: 143.00,
    targetPrice: 162.00,
    rMultiple: -0.4,
    holdingDays: 5,
    strategy: 'Swing',
    aiScore: 65,
    confidence: 52,
    hmmRegime: 'Neutral',
    alertLevel: 'warning',
    alertMessage: 'Approaching stop loss',
  },
  {
    symbol: 'AAPL',
    companyName: 'Apple Inc.',
    sector: 'Technology',
    quantity: 800,
    avgCost: 212.40,
    lastPrice: 218.90,
    marketValue: 175_120,
    todayPnl: 3_200,
    unrealizedPnl: 5_200,
    realizedPnl: 1_400,
    riskPercent: 1.2,
    allocationPercent: 7.2,
    stopPrice: 205.00,
    targetPrice: 235.00,
    rMultiple: 0.9,
    holdingDays: 22,
    strategy: 'Long-term',
    aiScore: 88,
    confidence: 79,
    hmmRegime: 'Bull',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'MSFT',
    companyName: 'Microsoft Corporation',
    sector: 'Technology',
    quantity: 300,
    avgCost: 410.20,
    lastPrice: 418.50,
    marketValue: 125_550,
    todayPnl: 1_890,
    unrealizedPnl: 2_490,
    realizedPnl: 0,
    riskPercent: 1.5,
    allocationPercent: 5.2,
    stopPrice: 398.00,
    targetPrice: 445.00,
    rMultiple: 0.7,
    holdingDays: 15,
    strategy: 'Long-term',
    aiScore: 86,
    confidence: 81,
    hmmRegime: 'Bull',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'META',
    companyName: 'Meta Platforms',
    sector: 'Technology',
    quantity: 150,
    avgCost: 475.30,
    lastPrice: 488.20,
    marketValue: 73_230,
    todayPnl: 1_935,
    unrealizedPnl: 1_935,
    realizedPnl: 3_200,
    riskPercent: 1.6,
    allocationPercent: 3.0,
    stopPrice: 460.00,
    targetPrice: 520.00,
    rMultiple: 0.8,
    holdingDays: 18,
    strategy: 'Momentum',
    aiScore: 91,
    confidence: 85,
    hmmRegime: 'Bull',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'JPM',
    companyName: 'JPMorgan Chase',
    sector: 'Financial',
    quantity: 400,
    avgCost: 198.40,
    lastPrice: 205.60,
    marketValue: 82_240,
    todayPnl: 2_400,
    unrealizedPnl: 2_880,
    realizedPnl: 1_600,
    riskPercent: 0.8,
    allocationPercent: 3.4,
    stopPrice: 192.00,
    targetPrice: 220.00,
    rMultiple: 1.1,
    holdingDays: 30,
    strategy: 'Swing',
    aiScore: 78,
    confidence: 71,
    hmmRegime: 'Bull',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'GS',
    companyName: 'Goldman Sachs',
    sector: 'Financial',
    quantity: 200,
    avgCost: 458.90,
    lastPrice: 472.30,
    marketValue: 94_460,
    todayPnl: 1_200,
    unrealizedPnl: 2_680,
    realizedPnl: 800,
    riskPercent: 1.1,
    allocationPercent: 3.9,
    stopPrice: 445.00,
    targetPrice: 500.00,
    rMultiple: 1.0,
    holdingDays: 14,
    strategy: 'Mean Reversion',
    aiScore: 74,
    confidence: 68,
    hmmRegime: 'Neutral',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'UNH',
    companyName: 'UnitedHealth Group',
    sector: 'Healthcare',
    quantity: 100,
    avgCost: 520.80,
    lastPrice: 508.40,
    marketValue: 50_840,
    todayPnl: -840,
    unrealizedPnl: -1_240,
    realizedPnl: 600,
    riskPercent: 1.3,
    allocationPercent: 2.1,
    stopPrice: 495.00,
    targetPrice: 560.00,
    rMultiple: -0.5,
    holdingDays: 7,
    strategy: 'Mean Reversion',
    aiScore: 62,
    confidence: 55,
    hmmRegime: 'Neutral',
    alertLevel: 'info',
    alertMessage: 'Earnings in 3 days',
  },
  {
    symbol: 'XOM',
    companyName: 'Exxon Mobil',
    sector: 'Energy',
    quantity: 600,
    avgCost: 112.40,
    lastPrice: 115.80,
    marketValue: 69_480,
    todayPnl: 1_080,
    unrealizedPnl: 2_040,
    realizedPnl: 900,
    riskPercent: 0.7,
    allocationPercent: 2.9,
    stopPrice: 108.00,
    targetPrice: 125.00,
    rMultiple: 0.8,
    holdingDays: 25,
    strategy: 'Income',
    aiScore: 72,
    confidence: 66,
    hmmRegime: 'Bull',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'TSLA',
    companyName: 'Tesla Inc.',
    sector: 'Consumer',
    quantity: -200,
    avgCost: 285.40,
    lastPrice: 278.60,
    marketValue: -55_720,
    todayPnl: 1_360,
    unrealizedPnl: 1_360,
    realizedPnl: 0,
    riskPercent: 2.4,
    allocationPercent: 2.3,
    stopPrice: 298.00,
    targetPrice: 255.00,
    rMultiple: 0.5,
    holdingDays: 3,
    strategy: 'Momentum',
    aiScore: 81,
    confidence: 73,
    hmmRegime: 'Bear',
    alertLevel: null,
    alertMessage: null,
  },
  {
    symbol: 'AMZN',
    companyName: 'Amazon.com',
    sector: 'Consumer',
    quantity: 250,
    avgCost: 188.90,
    lastPrice: 192.30,
    marketValue: 48_075,
    todayPnl: 625,
    unrealizedPnl: 850,
    realizedPnl: 1_500,
    riskPercent: 0.9,
    allocationPercent: 2.0,
    stopPrice: 182.00,
    targetPrice: 210.00,
    rMultiple: 0.5,
    holdingDays: 10,
    strategy: 'Swing',
    aiScore: 83,
    confidence: 76,
    hmmRegime: 'Bull',
    alertLevel: null,
    alertMessage: null,
  },
]

// ── Risk Metrics ───────────────────────────────────────

const mockRisk: RiskMetrics = {
  portfolioBeta: 1.28,
  portfolioDelta: 0.74,
  portfolioGamma: 0.03,
  portfolioVega: 0.18,
  portfolioTheta: -342.50,
  portfolioCorrelation: 0.68,
  var95: -48_200,
  var99: -78_600,
  expectedShortfall: -92_400,
  worstHistoricalLoss: -128_500,
  stressTestLoss: -185_000,
  kellyUtilization: 64,
  riskBudgetUsed: 82,
}

// ── Sector Exposure ────────────────────────────────────

const mockSectorExposure: SectorExposureItem[] = [
  { sector: 'Technology', percentage: 38, value: 610_230, color: 'hsl(215, 80%, 56%)' },
  { sector: 'Financial', percentage: 18, value: 176_700, color: 'hsl(145, 65%, 48%)' },
  { sector: 'Healthcare', percentage: 12, value: 50_840,  color: 'hsl(265, 60%, 60%)' },
  { sector: 'Energy', percentage: 8,  value: 69_480,  color: 'hsl(38, 90%, 55%)' },
  { sector: 'Consumer', percentage: 7,  value: 48_075,  color: 'hsl(0, 72%, 58%)' },
  { sector: 'Cash', percentage: 17, value: 412_350, color: 'hsl(220, 10%, 45%)' },
]

// ── Strategy Allocation ────────────────────────────────

const mockStrategyAllocation: StrategyAllocationItem[] = [
  { strategy: 'Momentum', percentage: 42, value: 255_650, color: 'hsl(215, 80%, 56%)' },
  { strategy: 'Swing', percentage: 28, value: 275_420, color: 'hsl(145, 65%, 48%)' },
  { strategy: 'Mean Reversion', percentage: 12, value: 145_300, color: 'hsl(265, 60%, 60%)' },
  { strategy: 'Long-term', percentage: 10, value: 300_670, color: 'hsl(38, 90%, 55%)' },
  { strategy: 'Income', percentage: 5, value: 69_480,  color: 'hsl(180, 60%, 48%)' },
  { strategy: 'Scalping', percentage: 3, value: 24_500,  color: 'hsl(0, 72%, 58%)' },
]

// ── Market Exposure ────────────────────────────────────

const mockMarketExposure: MarketExposureData = {
  longExposure: 1_805_325,
  shortExposure: 605_720,
  netExposure: 1_199_605,
  grossExposure: 2_411_045,
  betaAdjustedExposure: 981_200,
}

// ── Position Risk Ranking ──────────────────────────────

const mockPositionRisks: PositionRisk[] = [
  {
    symbol: 'AMD',
    riskScore: 94,
    reasons: ['High volatility', 'Approaching stop loss', 'Negative news catalyst'],
    severity: 'critical',
  },
  {
    symbol: 'TSLA',
    riskScore: 86,
    reasons: ['Short position', 'High IV environment', 'Earnings approaching'],
    severity: 'warning',
  },
  {
    symbol: 'PLTR',
    riskScore: 72,
    reasons: ['Sector concentration', 'Position size above target'],
    severity: 'warning',
  },
  {
    symbol: 'NVDA',
    riskScore: 68,
    reasons: ['Beta > 1.5', 'Correlated with PLTR/AMD'],
    severity: 'info',
  },
  {
    symbol: 'UNH',
    riskScore: 58,
    reasons: ['Earnings in 3 days', 'Below cost basis'],
    severity: 'info',
  },
]

// ── AI Position Health ─────────────────────────────────

const mockAIHealth: AIHealthItem[] = [
  { symbol: 'PLTR', stars: 5, state: 'Strong Buy', trend: 'Momentum Increasing', momentumDirection: 'up' },
  { symbol: 'META', stars: 5, state: 'Healthy', trend: 'Strong Uptrend', momentumDirection: 'up' },
  { symbol: 'NVDA', stars: 4, state: 'Healthy', trend: 'Stable', momentumDirection: 'flat' },
  { symbol: 'AAPL', stars: 4, state: 'Healthy', trend: 'Gradual Uptrend', momentumDirection: 'up' },
  { symbol: 'MSFT', stars: 4, state: 'Healthy', trend: 'Stable', momentumDirection: 'flat' },
  { symbol: 'AMZN', stars: 4, state: 'Recovering', trend: 'Bouncing Off Support', momentumDirection: 'up' },
  { symbol: 'JPM', stars: 3, state: 'Healthy', trend: 'Sector Rotation Possible', momentumDirection: 'flat' },
  { symbol: 'GS', stars: 3, state: 'Weakening', trend: 'Losing Momentum', momentumDirection: 'down' },
  { symbol: 'XOM', stars: 3, state: 'Healthy', trend: 'Range Bound', momentumDirection: 'flat' },
  { symbol: 'TSLA', stars: 3, state: 'Weakening', trend: 'Downtrend (Short Favorable)', momentumDirection: 'down' },
  { symbol: 'UNH', stars: 2, state: 'Weakening', trend: 'Pre-Earnings Uncertainty', momentumDirection: 'down' },
  { symbol: 'AMD', stars: 2, state: 'Breaking Down', trend: 'Exit Warning', momentumDirection: 'down' },
]

// ── Performance Attribution ────────────────────────────

const mockAttribution: PerformanceAttributionData = {
  bySector: [
    { name: 'Technology', pnl: 13_605 },
    { name: 'Financial', pnl: 3_600 },
    { name: 'Consumer', pnl: 1_985 },
    { name: 'Energy', pnl: 1_080 },
    { name: 'Healthcare', pnl: -840 },
  ],
  byStrategy: [
    { name: 'Momentum', pnl: 9_695 },
    { name: 'Swing', pnl: 3_895 },
    { name: 'Long-term', pnl: 5_090 },
    { name: 'Income', pnl: 1_080 },
    { name: 'Mean Reversion', pnl: 360 },
    { name: 'Scalping', pnl: -420 },
  ],
  byModel: [
    { name: 'AI Signals', pnl: 15_800 },
    { name: 'Manual', pnl: 4_200 },
  ],
}

// ── Open Orders ────────────────────────────────────────

const mockOpenOrders: PortfolioOrder[] = [
  { orderId: 'ORD-001', symbol: 'NVDA', side: 'BUY', orderType: 'LIMIT', quantity: 100, price: 178.50, status: 'SUBMITTED', createdAt: '2026-08-03T10:22:00Z' },
  { orderId: 'ORD-002', symbol: 'AMD', side: 'SELL', orderType: 'STOP', quantity: 500, price: 143.00, status: 'SUBMITTED', createdAt: '2026-08-03T09:45:00Z' },
  { orderId: 'ORD-003', symbol: 'TSLA', side: 'BUY', orderType: 'STOP', quantity: 200, price: 298.00, status: 'SUBMITTED', createdAt: '2026-08-03T11:10:00Z' },
  { orderId: 'ORD-004', symbol: 'AAPL', side: 'SELL', orderType: 'LIMIT', quantity: 200, price: 235.00, status: 'PENDING', createdAt: '2026-08-03T08:30:00Z' },
  { orderId: 'ORD-005', symbol: 'GS', side: 'SELL', orderType: 'TRAILING', quantity: 100, price: 468.50, status: 'SUBMITTED', createdAt: '2026-08-03T10:05:00Z' },
  { orderId: 'ORD-006', symbol: 'SPY', side: 'BUY', orderType: 'LIMIT', quantity: 500, price: 528.00, status: 'PENDING', createdAt: '2026-08-03T12:00:00Z' },
]

// ── Alerts ─────────────────────────────────────────────

const mockAlerts: PortfolioAlert[] = [
  { id: 'ALT-001', severity: 'critical', category: 'stop_triggered', message: 'AMD approaching stop loss ($143.00) — current $146.30', timestamp: '2026-08-03T14:22:00Z', symbol: 'AMD' },
  { id: 'ALT-002', severity: 'warning', category: 'beta_high', message: 'Portfolio beta 1.28 exceeds target 1.0', timestamp: '2026-08-03T13:45:00Z' },
  { id: 'ALT-003', severity: 'warning', category: 'sector_overweight', message: 'Technology sector 38% exceeds 30% limit', timestamp: '2026-08-03T12:30:00Z' },
  { id: 'ALT-004', severity: 'info', category: 'earnings', message: 'UNH earnings in 3 trading days', timestamp: '2026-08-03T09:00:00Z', symbol: 'UNH' },
  { id: 'ALT-005', severity: 'info', category: 'regime_change', message: 'AMD regime changed: Bull → Neutral', timestamp: '2026-08-03T10:15:00Z', symbol: 'AMD' },
  { id: 'ALT-006', severity: 'warning', category: 'ai_downgrade', message: 'GS AI score downgraded: 82 → 74', timestamp: '2026-08-03T11:20:00Z', symbol: 'GS' },
  { id: 'ALT-007', severity: 'low', category: 'correlation_spike', message: 'Tech correlation cluster at 0.86 (threshold: 0.80)', timestamp: '2026-08-03T10:45:00Z' },
]

// ── AI Recommendations ─────────────────────────────────

const mockRecommendations: AIRecommendation[] = [
  { id: 'REC-001', text: 'Reduce Tech Exposure (38% → target 30%)', priority: 'high', completed: false },
  { id: 'REC-002', text: 'Tighten Stops on AMD — Risk Score 94', priority: 'high', completed: false },
  { id: 'REC-003', text: 'Hedge with SPY puts (beta 1.28 → target 1.0)', priority: 'high', completed: false },
  { id: 'REC-004', text: 'PLTR nearing target $135.00 — consider scaling out', priority: 'medium', completed: false },
  { id: 'REC-005', text: 'Add Energy hedge — portfolio underweight', priority: 'medium', completed: false },
  { id: 'REC-006', text: 'Tech correlation 0.86 exceeding threshold', priority: 'medium', completed: false },
  { id: 'REC-007', text: 'Portfolio beta 1.28 above target 1.0', priority: 'low', completed: false },
  { id: 'REC-008', text: 'Review UNH position pre-earnings', priority: 'low', completed: false },
]

// ── Activity Timeline ──────────────────────────────────

const mockTimeline: TimelineEvent[] = [
  { id: 'TL-001', time: '09:31', type: 'trade', message: 'Bought PLTR 1000 @ 120.30', symbol: 'PLTR' },
  { id: 'TL-002', time: '09:42', type: 'trade', message: 'Bought NVDA 200 @ 175.80', symbol: 'NVDA' },
  { id: 'TL-003', time: '10:14', type: 'trade', message: 'Short TSLA 200 @ 285.40', symbol: 'TSLA' },
  { id: 'TL-004', time: '10:45', type: 'alert', message: 'Tech correlation spike: 0.86', symbol: undefined },
  { id: 'TL-005', time: '11:20', type: 'alert', message: 'AMD regime changed → Neutral', symbol: 'AMD' },
  { id: 'TL-006', time: '11:55', type: 'update', message: 'Stop updated: AMD $145.00 → $143.00', symbol: 'AMD' },
  { id: 'TL-007', time: '12:30', type: 'alert', message: 'Sector overweight alert: Tech 38%', symbol: undefined },
  { id: 'TL-008', time: '13:10', type: 'trade', message: 'Scaled out GS 50 @ 472.30', symbol: 'GS' },
  { id: 'TL-009', time: '14:22', type: 'alert', message: 'AMD approaching stop loss $143.00', symbol: 'AMD' },
  { id: 'TL-010', time: '15:41', type: 'milestone', message: 'New High Water Mark: $2,435,782', symbol: undefined },
]

// ── Export Aggregate Bundle ────────────────────────────

export const MOCK_PORTFOLIO_DATA: PortfolioData = {
  account: mockAccount,
  positions: mockPositions,
  risk: mockRisk,
  sectorExposure: mockSectorExposure,
  strategyAllocation: mockStrategyAllocation,
  marketExposure: mockMarketExposure,
  positionRisks: mockPositionRisks,
  aiHealth: mockAIHealth,
  attribution: mockAttribution,
  openOrders: mockOpenOrders,
  alerts: mockAlerts,
  recommendations: mockRecommendations,
  timeline: mockTimeline,
}
